name: hegra_holdings
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.17.5
  firebase_core: ^2.24.2
  

  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  get: ^4.6.5
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  

flutter:
  uses-material-design: true


  assets:
    - assets/images/icon.png
    - assets/images/mainlogo.png