// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBwF3L3BXIZsjm3We-17BmnUmXdGNThCc',
    appId: '1:611890438576:web:10676aa6a8ca8c7031b675',
    messagingSenderId: '611890438576',
    projectId: 'hegraholdings-9198d',
    authDomain: 'hegraholdings-9198d.firebaseapp.com',
    storageBucket: 'hegraholdings-9198d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsntoy1WCx7BHU0opH1ahR1apJofrGzCU',
    appId: '1:611890438576:android:8d23e80468c05d6131b675',
    messagingSenderId: '611890438576',
    projectId: 'hegraholdings-9198d',
    storageBucket: 'hegraholdings-9198d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDE1BGrFsAmcKnvCQqAVYPBunIBgrzX84',
    appId: '1:611890438576:ios:0935acac46422ae731b675',
    messagingSenderId: '611890438576',
    projectId: 'hegraholdings-9198d',
    storageBucket: 'hegraholdings-9198d.appspot.com',
    iosBundleId: 'com.example.hegraHoldings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDE1BGrFsAmcKnvCQqAVYPBunIBgrzX84',
    appId: '1:611890438576:ios:69e3c3093d69413c31b675',
    messagingSenderId: '611890438576',
    projectId: 'hegraholdings-9198d',
    storageBucket: 'hegraholdings-9198d.appspot.com',
    iosBundleId: 'com.example.hegraHoldings.RunnerTests',
  );
}
